name: video_player
description: A sample Polymer application
dependencies:
  core_elements: any
  paper_elements: any
  polymer: '>=0.12.0 <0.13.0'
transformers:
- polymer:
    entry_points: 
      - web/dualStreamExample.html
      - web/dualStreamWithSubtitlesExample.html
      - web/singleStreamExample.html
