name: video_player
authors:
- Hagen Echzell
- Georg Berecz
- Arne Boockmeyer
description: A dualStream-Videoplayer for openHPI
dependencies:
  core_elements: any
  custom_element_apigen: any
  paper_elements: any
  polymer: any
transformers:
- polymer:
    entry_points:
    - web/dualStreamExample.html
    - web/dualStreamWithSubtitlesExample.html
    - web/dualStreamWithThumbnailsExample.html
    - web/singleStreamExample.html
    js: true
- $dart2js:
    minify: false